# Output file path - where to write the repository context
output = 'output.txt'

# Include all files, ignore .gitignore rules
# noGitIgnore = false

# Include line numbers in file content output
# lineNumbers = true

# List recent modified files only
# recent

# Filter files by content pattern
# grep = ''

# File Filtering by Extension
# include = '*.md'