# Output file path - where to write the repository context
output = 'output.txt'

# Include all files, ignore .gitignore rules
noGitIgnore = false

# Include line numbers in file content output
lineNumbers = true

# List recent modified files (within last 5 days) only
recent = 5

# Include line numbers in file content output
grep = 'repomaster'